services:
  - type: web
    name: sandwich-shops-front
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
